<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Application',
        'AssetManager',
        'Channel',
        'Chat',
        'Console',
        'Emoji',
        'Ingest',
        'Outage',
        'Panel',
        'Root',
        'RTMP',
        'Search',
        'Status',
        'Stream',
        'Team',
        'Topic',
        'User',
        'Video',
        'ZF\\Apigility',
        'ZF\\Apigility\\Documentation',
        'ZF\\Apigility\\Provider',
        'ZF\\ApiProblem',
        'ZF\\Configuration',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\DevelopmentMode',
        'ZF\\Hal',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
        'config_cache_key' => 'application.config.cache',
        'config_cache_enabled' => true,
        'module_map_cache_key' => 'application.module.cache',
        'module_map_cache_enabled' => true,
        'cache_dir' => 'data/cache/',
    ),
);
