<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return array(
    'Application',
    'ZF\\DevelopmentMode',
    'ZF\\Apigility',
    'ZF\\Apigility\\Provider',
    'ZF\\Apigility\\Documentation',
    'AssetManager',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'Channel',
    'Chat',
    'Ingest',
    'Panel',
    'Root',
    'Search',
    'Status',
    'Stream',
    'Team',
    'Topic',
    'User',
    'Video',
);
